### PR TITLE
Adding build tags to source

### PR DESCRIPTION
**Pull request by vsiddharth**
Signed-off-by: Vinothkumar Siddharth <sidvin@amazon.com>

### CODE REVIEW

**Comment by vsiddharth** [comment]
@deniswernert Could you please have a look at this ?

**Review by d-tux — COMMENTED** [review]
Hi; thanks for contributing.
I'm not quite sure about this one; essentially you suggest we use the build tags to fail the build on a non-Linux platform. I get the idea, since udev is a Linux-only technology; however I'm not so sure that's the purpose behind build tags; I've always seen them as a way to provide platform dependent implementations.

Technically, the only file that won't compile because of platform dependent considerations is actually monitor.go, because it uses a Netlink socket.

Could you describe the use case that lead you to this change?

**Comment by vsiddharth** [comment]
I currently intend to use this library to monitor network interfaces and update a shared state. 
However this change is going into a bigger repository where a lot of them work out of non-Linux platforms and it would be great if this package worked only on supported platforms. 

Please have a look at this [PR](https://github.com/aws/amazon-ecs-agent/pull/701/files?short_path=32423b9#diff-32423b9aa8ba28656e469e42d18f12b6) for further information.

Please let me know if you have any other questions.

**Comment by d-tux** [comment]
OK; let's put it this way :) As of right now you're the sole user of this bit of code I know of, and from a pragmatic perspective it doesn't really change anything insofar it still builds on linux and fails on other platforms, so if it is helpful to you, let's merge it.

**Pull request merged**
